config/routes.rb
Isi::Application.routes.draw do
  get "slides/create"

  devise_for :admins
  
  root :to => "index#home"
  resources :projects, :only => [:index, :create, :show, :destroy] do
    resources :slides, :only => [:create, :destroy]
  end
  
  get "/design/criteria" => "design#criteria"
  get "/design/sizing" => "design#sizing"
  get "/design/site_questionnaire" => "design#site_questionnaire"
  get "/design/faq" => "design#faq"
  
  get "/technology/brushed_cylinder" => "technology#brushed_cylinder"
  get "/technology/brushed_cone" => "technology#brushed_cone"
  get "/technology/water_drive" => "technology#water_drive"
  
  get "/company/about" => "company#about"
  get "/company/clients" => "company#clients"
  get "/company/contact" => "company#contact"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  validate :must_be_isi_staff, :on => :save
  
private
  def must_be_isi_staff
    errors.add(:email, 'must be isi staff') unless self.email.split("@").last.downcase == "intakescreensinc.com"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :slides, :dependent => :destroy
  
  def cover_image
    return "//placehold.it/214x214" if self.slides.empty?
    self.slides.first.image.url(:thumb)
  end
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :project
  has_attached_file :image, :styles => {:original => "800x600>", :thumb => "214x214#"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end

end

app/controllers/design_controller.rb
class DesignController < ApplicationController
  def index
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @project = Project.new
  end
  
  def create
    @project = Project.create(params[:project])
    redirect_to projects_url, :notice => "Project successfully created"
  end
  
  def show
    @project = Project.find(params[:id])
    @slides = @project.slides
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  def create    
    slide = Slide.create(:image => params[:Filedata], :project_id => params[:project_id])
    render :json => {:success => true}
  end
  
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy
  end

end

app/controllers/technology_controller.rb
class TechnologyController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/design_helper.rb
module DesignHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def last_in_line(count)
    if count%4 == 0
      "last-in-line"
    end
  end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/technology_helper.rb
module TechnologyHelper
end

app/views/application/_footer.html.haml
.container
  .row
    %hr
    .twelve.columns
      %p.center
        Intake Screens Inc. | 
        8417 River Rd, Sacramento CA 95832 | 
        (916) 665-2727 | 
        CA Contractor License #796197 | 
        ="© Copyright #{DateTime.now.year}"

app/views/application/_navigation_bar.html.haml
.container
  .row
    #navigation.twelve.columns
      %dl.nice.contained.tabs.mobile
        %dd
          =active_link_to "Home", root_path
        %dd
          =active_link_to "Projects", projects_path, :active => /projects/i
        %dd
          =active_link_to "Technology", technology_brushed_cylinder_path, :active => /technology/i
        %dd
          =active_link_to "Design Info", design_criteria_path, :active => /design/i
        %dd
          =active_link_to "Company", company_about_path, :active => /company/i

app/views/company/about.html.haml
.container
  .row
    .eight.columns
      %h2 About
      
      %p Intake Screens, Inc. (ISI) has been delivering quality and innovative screens and projects since 1996.  ISI provides complete project and product services including: engineering design, manufacturing, fabrication, installation, and maintenance.  ISI is also a Class A General Engineerng Contractor in the State of California (CL#796197) and has the experience to handle simple to complex projects.   ISI’s facilities are located in Sacramento, CA.

      %p ISI’s success is based on a long history of working in the industry and its staff and owners bring together solid experience that is used on each project.  Russ Berry, founder of ISI, built the first self-cleaning intake screens on a ranch in north central Nebraska.  Seeing the great potential for a product that could solve suction related problems, he started manufacturing them in 1979.  In 1990, he sold Plum Creek Mfg. to the Claude Laval Corporation.  In 1996, Russ formed ISI to develop custom screens specifically for fish protection that could be used in demanding river environments.  In 1999, Russ’ son, Russell Berry IV, became involved in all aspects of the business, developing an impressive array of skill sets and abilities that he continues to build on and enjoy.  Darryl Hayes joined the comapny in 2006, bringing his fish facility and engineering expertise from his experiences at CH2M HILL and the California Department of Water Resources.  Darryl served as DWR’s Fish Facility Chief and lead the design of several large fish screen projects prior being at ISI.  Jacob Chapin also joined ISI in 2006, bringing his mechanical engineering expertise, fabrication, and CAD skills to the company.  Jacob’s resume includes designing fire trucks, heavy portable pump packages, and mechanical systems.  ISI’s staff also includes skilled fabricators and certified welders that can make about anything.

      %p Customers such as municipal water agencies, public utility districts, consulting engineering firms, irrigation districts, golf courses and farmers have all benefited from choosing ISI’s durable and efficient intake screens. ISI models have successfully protected pumping operations from debris and other contaminants, and provided wildlife protection that meets the requirements of state and federal environmental regulatory agencies.

      %p ISI’s achievements were recently recognized by NOAA Fisheries by receiving the Environmental Stewardship Award for Innovations in Fish Protection.

    .four.columns
      %h2 Key Personnel
      
      %h4 Russell Berry IV
      %h5 President
      %h6 rberry4@intakescreensinc.com
      %p Contact Russell for fabrication and manufacturing issues, quality control, and company related matters

      %h4 Russell (Russ) Berry III
      %h5 Vice President & Founder
      %h6 rberry3@intakescreensinc.com
      %p Contact Russ for information on agricultural/turf applications, water drive screens, product development, and company related matters

      %h4 Darryl Hayes, P.E.
      %h5 Engineering Manager
      %h6 dhayes@intakescreensinc.com
      %p Contact Darryl for cost estimating, project development, sales, engineering, and winemaking matters

      %h4 Jacob Chapin
      %h5 Mechanical Design Engineer
      %h6 jchapin@intakescreensinc.com
      %p Contact Jacob for fabrication and computer aided design questions

app/views/company/clients.html.haml
.container
  .row
    .twelve.columns
      %h2 Some of Our Clients
      
      =image_tag "/static/clients.png"
      
      %p ISI has worked with many engineering firms, regulatory agencies, municipalities, non-profits, and various private interests.  Below are just a few of our partners and clients that we have collaboratively worked with.  Project references are available upon request.

app/views/design/criteria.html.haml
.container
  .row
    .twelve.columns
      %h2 Fish Screen Design Criteria
      
      %h3 General
      %p Intake screens are typically designed to protect fish from being entrained into a diversion AND to prevent them from being impinged on the screen surface.  This means that the screen openings must be small enough to keep the fish out and that there is enough screen area to allow the fish to swim away without injury.  There are also requirements for providing good hydraulic conditions, keeping the screens clean, and for siting them appropriately in a river, canal, or lake environment.

      %p Several state and federal agencies have guidelines and design criteria for fish protection.  Generally the more conservative criteria will govern; however, there are variances and exceptions to these guidelines since each project is unique.  A well designed facility will also consider the pump or diversion requirements as well as operations and maintenance issues.

      %p ISI’s engineers are familiar with the regulatory design requirements and are experienced in selecting an appropriate design for your new or retrofit project.  We can guide you through the complicated design issues and determine which options makes the most sense - even if an ISI screen is not the most appropriate option!

      %p Below we have referenced several intake screen design criteria that may be applicable to your project.  Please review our project examples to see if your project has similar needs.  Please call us to assist.

app/views/index/home.html.haml
:javascript
  $(window).load(function() {
       $('#slider').orbit({fluid:true, animation: 'fade', advanceSpeed: 4000, animationSpeed:1000});
   });

.container
  .row
    .twelve.columns
      %h4 Brush-Cleaned Wedgewire Intake Screens for Fish Protection and Filtration
      #slider
        =image_tag "/static/slide3.jpg"
    
  .row
    .twelve.columns
      %ul
        %li ISI offers innovative screening options with patented and proven features
        %li Brush-cleaned screens are effective alternatives to typical air-burst cleaning and water-backwash systems
        %li ISI’s experienced engineers can assist you in designing new or retrofit facilities with full regulatory compliance
        %li Design-Build capabilities, including full service custom metal fabrication, manufacturing, and installation
        %li Experienced on diversions ranging from 1 to 1450 cfs with typical wedgewire slot sizes less than 2 mm

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Intake Screens, Inc.
    =stylesheet_link_tag "application", params[:controller]
    =yield :js_variables
    =javascript_include_tag "application"
    =csrf_meta_tags
  
  %body
    .container
      .row
        .twelve.columns
          #header
            =image_tag "/static/logo.png", :id => "logo"
            %h1 Intake Screens, Inc.
    =render "navigation_bar"
    =yield
    =render "footer"

app/views/projects/destroy.js.erb
$("#project_<%= @project.id %>").fadeOut("slow")

app/views/projects/index.html.haml
.container
  .row
    .twelve.columns
      %a.nice.medium.blue.radius.button{:"data-reveal-id" => "addAnotherProject"} Add Another Project
      %hr
  .row
    .twelve.columns
      -@projects.each_with_index do |project, index|
        =content_tag_for :div, project, :class => "#{last_in_line(index+1)}" do
          =link_to project do
            =image_tag project.cover_image
          .trash=link_to "Destroy", project, :method => :delete, :remote => true, :confirm => "Do you really want to remove this project?"
          %h6= project.name

#addAnotherProject.reveal-modal
  %h3 Tell me about the project
  =form_for @project, :html => {:class => "nice"} do |f|
    %label
      %strong What's the name of the project?
      =f.text_field :name, :class => "input-text", :placeholder => "Redding Power Plant ..."
    %label
      %strong Where was the project take place?
      %input.input-text.large{:placeholder => "Redding, CA"}
    %label
      %strong What types of screens were used?
      %input.input-text.large{:placeholder => "2 ISI C-44"}
    %button.nice.small.blue.radius.button{:type=>"submit"} Create Project
  %a.close-reveal-modal &#215;

app/views/projects/show.html.haml
-content_for :js_variables do
  :javascript
    var ISI = {};
    ISI.upload_url = "#{project_slides_path(@project)}";
    ISI.multipart_params = {
      '#{request_forgery_protection_token}': '#{form_authenticity_token}',
      '#{request.session_options[:key]}': '#{request.session_options[:id]}'
    }

.container
  .row
    .twelve.columns
      %a#addPhotos.nice.medium.blue.radius.button Add Photos
      .loading.right
      %hr
      
  .row
    .twelve.columns
      %h2= @project.name
      
      -@slides.each_with_index do |slide, index|
        =content_tag_for :div, slide, :class => "project #{last_in_line(index+1)}" do
          =image_tag slide.image.url(:thumb)
          .trash= link_to "Destroy", project_slide_path(@project, slide), :method => :delete, :remote => true, :confirm => "Do you really want to remove this photo?"

app/views/slides/destroy.js.erb
$("#slide_<%= @slide.id %>").fadeOut("slow");

app/views/technology/brushed_cone.html.haml
.container
  .row
    .twelve.columns
      %h2 Brushed Cone for Shallow Intakes
      
      %h3 Summary
      %ul
        %li Designs for shallow water, tidal esturaries, and silty conditions
        %li Protects fish from entrainment or impingement
        %li Protects pump from clogging debris
        %li Protects downstream filtration and irrigation equipment
      
      %h3 Key Features
      %ul
        %li Screen can be used even if not fully submerged
        %li Positive brushing action prevents debris buildup, sedimentation, and bio-fouling
        %li Cone shaped design is very strong and hydraulically efficient
        %li Easy to install and remove onto various base designs
        %li Internal flow baffle distributes flow evenly across the screen surface
        %li Marine-duty hydraulic drive motor rotates cleaning brushes
        %li Control panel allows user defined cleaning cycles
      
      %h3 Options & Customization
      %ul
        %li Minimal power requirements
        %li Solar power options available
        %li Interfaces with customer’s SCADA controls for remote monitoring and control
        %li Control panels to match customers equipment
        %li Wedgewire slot width options from 1 mm to 9 mm
        %li Screen design and construction for extreme design loads
        %li Screen base diameters up to 15 feet to meet application needs

app/views/technology/brushed_cylinder.html.haml
.container
  .row
    .twelve.columns
      %h2 Brushed Cylinder for Submerged Intakes
      
      
      %h3 Summary
      %ul
        %li Protect fish from entrainment and impingement
        %li Protect pumps from clogging
        %li Protect downstream filtration and irrigation equipment
      %h3 Key Features
      %ul
        %li Cylinders concentrate a large amount of surface into a small area
        %li Strong stainless steel construction with wedgewire cylinders provide durability
        %li Powerful and thorough brushing inside and out keeps the screen clean and free of debris
        %li Even flow distribution along the screen surface
        %li Retrievable design allows easy access for maintenance
        %li Cathodically protected to minimize corrosion
      %h3 Control & Power Features
      %ul
        %li Marine-duty hydraulic drive motor rotates cylinder for brush-cleaning
        %li Control panel allows user defined cleaning cycles
        %li Minimal power requirements
        %li Solar power option
        %li Propeller drive option
        %li Interfaces with customer’s SCADA controls
      %h3 Customization
      %ul
        %li Wedgewire slot width options from 0.5 mm to 9 mm
        %li Design for extreme conditions, including ice, debris, currents and hydrostatic forces
        %li Control panel options to match customer’s equipment if necessary
        %li Screen lengths and diameters to meet application needs

app/views/technology/water_drive.html.haml
.container
  .row
    .twelve.columns
      %h2 Water Drive


      %h3 Summary
      %ul
        %li Lightweight design for small pump installations
        %li Cleans using water pressure from pump
        %li Filtration on the suction side of the pump reduces maintenance
        %li Protects pumps and downstream irrigation equipment
        %li Designed for pumps between 300 and 1700 gpm

      %h3 Key Features
      %ul
        %li Neutrally buoyant rotating screen reduces stress and wear while improving rotation
        %li Wedgewire screen has 50% or more open area to reduce clogging issues and is many times stronger than wire cloth or perforated metal
        %li Strong and durable screen construction for long-life in difficult operating environments - withstands 20+ inches of vacuum
        %li Rotation sensor for operation verification
        %li Sealed thrust bearing allows intake pipe to connect to screen at any angle
        %li All stainless steel and plastic construction minimizes corrosion
        %li Design based on over 30 years experience in the business!
      %h3 Options & Customization
      %ul
        %li Rotation sensor can be connected to emergency pump shutoff
        %li Antifouling coating on wedgewire available
        %li Brush cleaner available with propeller drive option
        %li Slotted openings between 1 mm and 1.75 mm available